10 DEF SQR(X#) = X# * X#
20 DEF MUL(X#, Y#) = X# * Y#
30 A# = SQR(3)
40 B# = MUL(A#, 4)
50 IF A# <> 9 THEN PRINT "SQR FAIL" ELSE PRINT "SQR PASS"
60 IF B# <> 36 THEN PRINT "MUL FAIL" ELSE PRINT "MUL PASS"
